# ./.pre-commit-config.yaml

repos:
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.12
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.0
    hooks:
      - id: mypy
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort